version: 2.1
orbs:
  python: circleci/python@2.1.1

parameters:
  eval-mode:
    type: string
    default: "commit"

workflows:
  evaluate-app:  
    jobs:
      - run-hello-world:
          context:
            - dl-ai-courses
jobs:
  run-hello-world: 
    docker:
      - image: cimg/python:3.10.5
    steps:
      - run:
          name: Print Hello World
          command: echo "Hello World!"
